apiVersion: v1
kind: Service
metadata:
  name: wow-web
  namespace: wow-refund
  labels:
    app.kubernetes.io/name: wow-refund
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: wow-refund
    app.kubernetes.io/component: web
